import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@mantine/core/styles.css";
import "mantine-react-table/styles.css";
import { ColorSchemeScript, MantineProvider } from "@mantine/core";
import Providers from "@/lib/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>My awesome app</title>
        <ColorSchemeScript />
      </head>
      <Providers>
        <body className={inter.className}>
          <MantineProvider>{children}</MantineProvider>
        </body>
      </Providers>
    </html>
  );
}
