version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: masrealestate
      POSTGRES_DB: real-estate
    volumes:
      - type: bind
        source: /root/volumes/real-estate/db
        target: /var/lib/postgresql/db
    restart: unless-stopped

  server:
    stdin_open: true
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server-container
    depends_on:
      - postgres
    ports:
      - 7000:7000
      - 4000:4000
    volumes:
      - type: bind
        source: /root/volumes/real-estate/data
        target: /app/data

  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client-container
    depends_on:
      - postgres
    ports:
      - 3000:3000