version: "3.9"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    hostname: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: managerrealestate
      POSTGRES_DB: real_estate
    volumes:
      - type: bind
        source: /root/volumes/real-estate/db
        target: /var/lib/postgresql/db
    restart: unless-stopped

  server:
    stdin_open: true
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server-container
    depends_on:
      - postgres
    ports:
      - 7000:7000
      - 4000:4000
    volumes:
      - type: bind
        source: /root/volumes/real-estate/data
        target: /app/data

  client:
    stdin_open: true
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client-container
    depends_on:
      - postgres
    ports:
      - 3000:3000

  dashboard:
    stdin_open: true
    build:
      context: ./dashboard
      dockerfile: Dockerfile
    container_name: dashboard-container
    depends_on:
      - server
    ports:
      - 3200:3200

  backup-service:
    build:
      context: ./backup-service
    container_name: backup-service
    volumes:
      - type: bind
        # source: C:/data/backup
        source: /var/backups
        target: /backup
    depends_on:
      - postgres
    restart: unless-stopped
